package AnalizadorJson;
import java_cup.runtime.*;
import java.util.ArrayList;
import java.util.List;
import ReportesHtml.ReporteError;
import ReportesHtml.ReporteToken;


parser code {:
    public void syntax_error(Symbol s){
        String lexema = (String) s.value;
        String descripcion = "Error sintáctico";
        int linea = s.left + 1;
        int columna = s.right + 1;

        // crear objeto de reporte error
        ReporteError error = new ReporteError(lexema, descripcion, linea, columna);

        // se añade error a la lista de errores
        ReporteError.errorList.add(error);

        System.out.println("Error sintáctico: "+ s.value +" Linea "+(s.left+1)+" columna "+(s.right+1) );
    }

    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{ 
        System.out.println("Error sintáctico: "+ s.value +" Linea "+(s.left+1)+" columna "+(s.right+1) );
    }

    String tmp="";


        // Creo una lista de tipo String llamada 'resultados', donde guardare cada uno de los resultados analizados
        public List<String> resultados = new ArrayList<String>();
:}




/* Terminales */
terminal COMILLA;
terminal String STRING, DOUBLE;
terminal LLAV_A;
terminal COMA;
terminal DOSPTS;
terminal LLAV_C;

/* No Terminales */
nonterminal inicio, elementos, elemento, clave, valor, lista;

/* Producciones */
start with inicio;

inicio ::= LLAV_A elementos LLAV_C;

elementos ::= elemento
            | elementos COMA elemento;

elemento ::= STRING:clave DOSPTS DOUBLE:valor
            {:
                    JsonHashTable.add(clave,valor);
                    String clav = JsonHashTable.get(clave);
                    System.out.println("Added key: " + clave + ", value: " + valor + " to jsonHash");           
                    System.out.println(clav);
            :}
    | STRING:clave1 DOSPTS STRING:valor1
            {:
                    JsonHashTable.add(clave1,valor1);
                    String clav1 = JsonHashTable.get(clave1);
                    System.out.println("Added key: " + clave1 + ", value: " + valor1 + " to jsonHash");         
                    System.out.println(clav1);                 
            :}
;


