
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package AnalizadorJson;

import java.util.ArrayList;
import java.util.List;
import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class SintacticoJson extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public SintacticoJson() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public SintacticoJson(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public SintacticoJson(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\013\000\002\002\004\000\002\002\005\000\002\003" +
    "\003\000\002\003\005\000\002\004\005\000\002\005\003" +
    "\000\002\006\003\000\002\006\003\000\002\006\005\000" +
    "\002\007\003\000\002\007\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\025\000\004\006\004\001\002\000\004\005\010\001" +
    "\002\000\004\002\006\001\002\000\004\002\001\001\002" +
    "\000\006\010\uffff\012\uffff\001\002\000\004\011\ufffc\001" +
    "\002\000\004\011\016\001\002\000\006\010\013\012\014" +
    "\001\002\000\004\005\010\001\002\000\004\002\000\001" +
    "\002\000\006\010\ufffe\012\ufffe\001\002\000\010\005\020" +
    "\006\017\007\021\001\002\000\010\005\020\006\017\007" +
    "\021\001\002\000\006\010\ufffb\012\ufffb\001\002\000\006" +
    "\010\ufffa\012\ufffa\001\002\000\006\010\ufffd\012\ufffd\001" +
    "\002\000\006\010\ufff8\012\ufff8\001\002\000\006\010\025" +
    "\012\026\001\002\000\010\005\020\006\017\007\021\001" +
    "\002\000\006\010\ufff9\012\ufff9\001\002\000\006\010\ufff7" +
    "\012\ufff7\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\025\000\004\002\004\001\001\000\010\003\011\004" +
    "\006\005\010\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\004\014\005\010\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\006\021\001\001\000" +
    "\006\006\022\007\023\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\006\026\001\001\000\002\001\001\000\002" +
    "\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$SintacticoJson$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$SintacticoJson$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$SintacticoJson$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public void syntax_error(Symbol s){
        System.out.println("Error sintáctico: "+ s.value +" Linea "+(s.left+1)+" columna "+(s.right+1) );
    }

    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{ 
        System.out.println("Error sintáctico: "+ s.value +" Linea "+(s.left+1)+" columna "+(s.right+1) );
    }
    String tmp="";

    //Clases, objetos, variables, lista, etc... en sintaxis java
    
    //Creo una lista de tipo String llamada 'resultados', donde guardare cada uno de los resultados analizados
    public List<String> resultados = new ArrayList<String>();


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$SintacticoJson$actions {
  private final SintacticoJson parser;

  /** Constructor */
  CUP$SintacticoJson$actions(SintacticoJson parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$SintacticoJson$do_action_part00000000(
    int                        CUP$SintacticoJson$act_num,
    java_cup.runtime.lr_parser CUP$SintacticoJson$parser,
    java.util.Stack            CUP$SintacticoJson$stack,
    int                        CUP$SintacticoJson$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$SintacticoJson$result;

      /* select the action based on the action number */
      switch (CUP$SintacticoJson$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= inicio EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$SintacticoJson$stack.elementAt(CUP$SintacticoJson$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$SintacticoJson$stack.elementAt(CUP$SintacticoJson$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$SintacticoJson$stack.elementAt(CUP$SintacticoJson$top-1)).value;
		RESULT = start_val;
              CUP$SintacticoJson$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$SintacticoJson$stack.elementAt(CUP$SintacticoJson$top-1)), ((java_cup.runtime.Symbol)CUP$SintacticoJson$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$SintacticoJson$parser.done_parsing();
          return CUP$SintacticoJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // inicio ::= LLAV_A elementos LLAV_C 
            {
              Object RESULT =null;

              CUP$SintacticoJson$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$SintacticoJson$stack.elementAt(CUP$SintacticoJson$top-2)), ((java_cup.runtime.Symbol)CUP$SintacticoJson$stack.peek()), RESULT);
            }
          return CUP$SintacticoJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // elementos ::= elemento 
            {
              Object RESULT =null;

              CUP$SintacticoJson$result = parser.getSymbolFactory().newSymbol("elementos",1, ((java_cup.runtime.Symbol)CUP$SintacticoJson$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoJson$stack.peek()), RESULT);
            }
          return CUP$SintacticoJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // elementos ::= elementos COMA elemento 
            {
              Object RESULT =null;

              CUP$SintacticoJson$result = parser.getSymbolFactory().newSymbol("elementos",1, ((java_cup.runtime.Symbol)CUP$SintacticoJson$stack.elementAt(CUP$SintacticoJson$top-2)), ((java_cup.runtime.Symbol)CUP$SintacticoJson$stack.peek()), RESULT);
            }
          return CUP$SintacticoJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // elemento ::= clave DOSPTS valor 
            {
              Object RESULT =null;

              CUP$SintacticoJson$result = parser.getSymbolFactory().newSymbol("elemento",2, ((java_cup.runtime.Symbol)CUP$SintacticoJson$stack.elementAt(CUP$SintacticoJson$top-2)), ((java_cup.runtime.Symbol)CUP$SintacticoJson$stack.peek()), RESULT);
            }
          return CUP$SintacticoJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // clave ::= STRING 
            {
              Object RESULT =null;

              CUP$SintacticoJson$result = parser.getSymbolFactory().newSymbol("clave",3, ((java_cup.runtime.Symbol)CUP$SintacticoJson$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoJson$stack.peek()), RESULT);
            }
          return CUP$SintacticoJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // valor ::= STRING 
            {
              Object RESULT =null;

              CUP$SintacticoJson$result = parser.getSymbolFactory().newSymbol("valor",4, ((java_cup.runtime.Symbol)CUP$SintacticoJson$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoJson$stack.peek()), RESULT);
            }
          return CUP$SintacticoJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // valor ::= DOUBLE 
            {
              Object RESULT =null;

              CUP$SintacticoJson$result = parser.getSymbolFactory().newSymbol("valor",4, ((java_cup.runtime.Symbol)CUP$SintacticoJson$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoJson$stack.peek()), RESULT);
            }
          return CUP$SintacticoJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // valor ::= LLAV_A lista LLAV_C 
            {
              Object RESULT =null;

              CUP$SintacticoJson$result = parser.getSymbolFactory().newSymbol("valor",4, ((java_cup.runtime.Symbol)CUP$SintacticoJson$stack.elementAt(CUP$SintacticoJson$top-2)), ((java_cup.runtime.Symbol)CUP$SintacticoJson$stack.peek()), RESULT);
            }
          return CUP$SintacticoJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // lista ::= valor 
            {
              Object RESULT =null;

              CUP$SintacticoJson$result = parser.getSymbolFactory().newSymbol("lista",5, ((java_cup.runtime.Symbol)CUP$SintacticoJson$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoJson$stack.peek()), RESULT);
            }
          return CUP$SintacticoJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // lista ::= lista COMA valor 
            {
              Object RESULT =null;

              CUP$SintacticoJson$result = parser.getSymbolFactory().newSymbol("lista",5, ((java_cup.runtime.Symbol)CUP$SintacticoJson$stack.elementAt(CUP$SintacticoJson$top-2)), ((java_cup.runtime.Symbol)CUP$SintacticoJson$stack.peek()), RESULT);
            }
          return CUP$SintacticoJson$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$SintacticoJson$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$SintacticoJson$do_action(
    int                        CUP$SintacticoJson$act_num,
    java_cup.runtime.lr_parser CUP$SintacticoJson$parser,
    java.util.Stack            CUP$SintacticoJson$stack,
    int                        CUP$SintacticoJson$top)
    throws java.lang.Exception
    {
              return CUP$SintacticoJson$do_action_part00000000(
                               CUP$SintacticoJson$act_num,
                               CUP$SintacticoJson$parser,
                               CUP$SintacticoJson$stack,
                               CUP$SintacticoJson$top);
    }
}

}
