
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package AnalizadorJson;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMA = 6;
  public static final int EOF = 0;
  public static final int STRING = 3;
  public static final int LLAV_C = 8;
  public static final int DOUBLE = 4;
  public static final int LLAV_A = 5;
  public static final int error = 1;
  public static final int DOSPTS = 7;
  public static final int COMILLA = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMILLA",
  "STRING",
  "DOUBLE",
  "LLAV_A",
  "COMA",
  "DOSPTS",
  "LLAV_C"
  };
}

