
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package AnalizadorStatpy;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INT1 = 5;
  public static final int MULT = 24;
  public static final int comentario2 = 21;
  public static final int ENTERO = 3;
  public static final int CASE = 39;
  public static final int DOUBLE = 18;
  public static final int RESTA = 23;
  public static final int PRI = 11;
  public static final int FOR = 42;
  public static final int WRITE = 17;
  public static final int PUB = 10;
  public static final int NOT = 34;
  public static final int AND = 32;
  public static final int ELSEIF = 37;
  public static final int IGUAL = 30;
  public static final int OR = 33;
  public static final int STRING1 = 9;
  public static final int DIV = 25;
  public static final int ASIGNA = 50;
  public static final int CHAR1 = 6;
  public static final int SUMA = 22;
  public static final int IF = 36;
  public static final int MAIN = 13;
  public static final int LLAV_C = 47;
  public static final int ID = 2;
  public static final int LLAV_A = 46;
  public static final int PYCOMA = 49;
  public static final int DIST = 31;
  public static final int VOI = 12;
  public static final int EOF = 0;
  public static final int DECIMAL = 19;
  public static final int error = 1;
  public static final int MAYOR_I = 28;
  public static final int COMA = 48;
  public static final int CADENA = 4;
  public static final int MENOR = 27;
  public static final int PAR_C = 45;
  public static final int COMILLA_S = 35;
  public static final int PAR_A = 44;
  public static final int BREAK = 40;
  public static final int MENOR_I = 29;
  public static final int SWITCH = 38;
  public static final int MAYOR = 26;
  public static final int PUNTO = 14;
  public static final int WHILE = 43;
  public static final int DEFAULT = 41;
  public static final int DOSP = 15;
  public static final int comentario = 20;
  public static final int BOOL1 = 8;
  public static final int DOUBLE1 = 7;
  public static final int CONSOLE = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "ENTERO",
  "CADENA",
  "INT1",
  "CHAR1",
  "DOUBLE1",
  "BOOL1",
  "STRING1",
  "PUB",
  "PRI",
  "VOI",
  "MAIN",
  "PUNTO",
  "DOSP",
  "CONSOLE",
  "WRITE",
  "DOUBLE",
  "DECIMAL",
  "comentario",
  "comentario2",
  "SUMA",
  "RESTA",
  "MULT",
  "DIV",
  "MAYOR",
  "MENOR",
  "MAYOR_I",
  "MENOR_I",
  "IGUAL",
  "DIST",
  "AND",
  "OR",
  "NOT",
  "COMILLA_S",
  "IF",
  "ELSEIF",
  "SWITCH",
  "CASE",
  "BREAK",
  "DEFAULT",
  "FOR",
  "WHILE",
  "PAR_A",
  "PAR_C",
  "LLAV_A",
  "LLAV_C",
  "COMA",
  "PYCOMA",
  "ASIGNA"
  };
}

